version: '3.8'

services:
  db:
    image: postgres:15
    container_name: meme_search_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meme_search
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    container_name: meme_search_bot
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data:
